[licenses]
unused-allowed-license = "allow"
confidence-threshold = 0.95

allow = [
    "Apache-2.0",
    # This isn't explicitly called out as allowed, but I'm counting it as covered under Apache-2.0
    "Apache-2.0 WITH LLVM-exception",
    # We follow the CNCF list of allowed non-Apache-2.0 licenses. All allowed licenses are included to minimize the need to update this list in the future.
    # https://github.com/cncf/foundation/blob/main/policies-guidance/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
    "0BSD",
    "BSD-2-Clause",
    "BSD-2-Clause-FreeBSD",
    "BSD-3-Clause",
    "MIT",
    "MIT-0",
    "ISC",
    "OpenSSL",
    "OpenSSL-standalone",
    "PSF-2.0",
    "Python-2.0",
    "Python-2.0.1",
    "PostgreSQL",
    "SSLeay-standalone",
    "UPL-1.0",
    "X11",
    "Zlib",
    # TODO: These licenses are not in the CNCF allow-list, but were approved for use by AWS and are the licenses for current dependencies.
    "Unicode-DFS-2016",
    "Unicode-3.0",
]
